image: 'Visual Studio 2017'
build: off
test_script:
  cmd: |
      git submodule update --init --recursive
      nuget restore
      dotnet build -c Release ./OhmGraphite/OhmGraphite.csproj
      dotnet test .\OhmGraphite.Test\OhmGraphite.Test.csproj
