version: '3'
services:
  influx:
    image: influxdb:alpine
    environment:
      INFLUXDB_DB: "mydb"
      INFLUXDB_USER: "my_user"
      INFLUXDB_USER_PASSWORD: "my_pass"
  redis:
    image: redis:alpine
  graphite:
    build:
      dockerfile: Dockerfile.graphite
      context: ci
    depends_on:
      - redis
  timescale:
    build:
      dockerfile: ci/Dockerfile.timescale
      context: .
    environment:
      POSTGRES_PASSWORD: 123456
  app:
    build:
      dockerfile: ci/Dockerfile.tests
      context: .
    privileged: true
    depends_on:
      - timescale
      - graphite
      - influx
    command: ./ci/wait-for-it.sh timescale:5432 -- ./ci/wait-for-it.sh graphite:80 -- mono /root/.nuget/packages/xunit.runner.console/2.4.0/tools/net461/xunit.console.exe OhmGraphite.Test/bin/Debug/net461/OhmGraphite.Test.dll
